import '../screens/actionScreen.dart';

class AbsBeginnerNavigator {
  static List<ActionScreen> list = [
    ActionScreen(
      title: 'Jumping Jacks',
      number: 15,
      gifDirectory: "assets/gifs/jumpingJack.gif",
      frameMin: 0,
      frameMax: 40,
      milisecondAnimation: 1500,
      milisecondTimer: 1500,
      sessionNumber: 1,
    ),
    ActionScreen(
      title: 'High Stepping',
      number: 20,
      gifDirectory: "assets/gifs/highStepping.gif",
      frameMin: 0,
      frameMax: 17,
      milisecondAnimation: 1000,
      milisecondTimer: 1000,
      sessionNumber: 2,
    ),
    ActionScreen(
      title: 'Russians Twist',
      number: 12,
      gifDirectory: "assets/gifs/RussianTwists.gif",
      frameMin: 0,
      frameMax: 40,
      milisecondAnimation: 3000,
      milisecondTimer: 1000,
      sessionNumber: 3,
    ),
    ActionScreen(
      title: 'Mountain Climber',
      number: 15,
      gifDirectory: "assets/gifs/mountain-climber.gif",
      frameMin: 0,
      frameMax: 4,
      milisecondAnimation: 2500,
      milisecondTimer: 1250,
      sessionNumber: 4,
    ),
    ActionScreen(
      title: 'Leg Raises',
      number: 10,
      gifDirectory: "assets/gifs/legRaises.gif",
      frameMin: 0,
      frameMax: 140,
      milisecondAnimation: 3000,
      milisecondTimer: 3000,
      sessionNumber: 5,
    ),
    ActionScreen(
      title: 'Skipping Without Rope',
      number: 20,
      gifDirectory: "assets/gifs/jump-rope.gif",
      frameMin: 0,
      frameMax: 9,
      milisecondAnimation: 400,
      milisecondTimer: 800,
      sessionNumber: 6,
    ),
    ActionScreen(
      title: 'Plank',
      number: 20,
      gifDirectory: "assets/gifs/plank.gif",
      frameMin: 100,
      frameMax: 180,
      milisecondAnimation: 3000,
      milisecondTimer: 2000,
      sessionNumber: 7,
    ),
    ActionScreen(
      title: 'Cobra Stretch',
      number: 15,
      gifDirectory: "assets/gifs/cobra-stretch.gif",
      frameMin: 0,
      frameMax: 7,
      milisecondAnimation: 3000,
      milisecondTimer: 3000,
      sessionNumber: 8,
    ),
    ActionScreen(
      title: 'Lying Twist Stretch',
      number: 10,
      gifDirectory: "assets/gifs/lyingTwistStretch.gif",
      frameMin: 0,
      frameMax: 4,
      milisecondAnimation: 3000,
      milisecondTimer: 3000,
      sessionNumber: 9,
    ),
    ActionScreen(
      title: 'Flutter Kicks',
      number: 18,
      gifDirectory: "assets/gifs/flutter-kicks.gif",
      frameMin: 5,
      frameMax: 90,
      milisecondAnimation: 3000,
      milisecondTimer: 1000,
      sessionNumber: 10,
    ),
    ActionScreen(
      title: 'Leg Raises',
      number: 10,
      gifDirectory: "assets/gifs/legRaises.gif",
      frameMin: 0,
      frameMax: 140,
      milisecondAnimation: 3500,
      milisecondTimer: 3500,
      sessionNumber: 11,
    ),
    ActionScreen(
      title: 'Russians Twist',
      number: 14,
      gifDirectory: "assets/gifs/RussianTwists.gif",
      frameMin: 0,
      frameMax: 40,
      milisecondAnimation: 3000,
      milisecondTimer: 1000,
      sessionNumber: 12,
    ),
    ActionScreen(
      title: 'Mountain Climber',
      number: 16,
      gifDirectory: "assets/gifs/mountain-climber.gif",
      frameMin: 0,
      frameMax: 4,
      milisecondAnimation: 2500,
      milisecondTimer: 1250,
      sessionNumber: 13,
    ),
    ActionScreen(
      title: 'Jumping Jacks',
      number: 10,
      gifDirectory: "assets/gifs/jumpingJack.gif",
      frameMin: 0,
      frameMax: 40,
      milisecondAnimation: 1000,
      milisecondTimer: 1000,
      sessionNumber: 14,
    ),
    ActionScreen(
        title: 'High Stepping',
        number: 15,
        gifDirectory: "assets/gifs/highStepping.gif",
        frameMin: 0,
        frameMax: 17,
        milisecondAnimation: 800,
        milisecondTimer: 800,
        sessionNumber: 15),
    ActionScreen(
        title: 'Cobra Stretch',
        number: 15,
        gifDirectory: "assets/gifs/cobra-stretch.gif",
        frameMin: 0,
        frameMax: 7,
        milisecondAnimation: 3000,
        milisecondTimer: 3000,
        sessionNumber: 16),
  ];
}
