import '../screens/actionScreen.dart';

class AbsAdvanceNavigator {
  static List<ActionScreen> list = [
    ActionScreen(
      title: 'Jumping Jacks',
      number: 14,
      gifDirectory: "assets/gifs/jumpingJack.gif",
      frameMin: 0,
      frameMax: 40,
      milisecondAnimation: 1000,
      milisecondTimer: 1000,
      sessionNumber: 1,
    ),
    ActionScreen( 
      title: 'High Stepping',
      number: 12,
      gifDirectory: "assets/gifs/highStepping.gif",
      frameMin: 0,
      frameMax: 17,
      milisecondAnimation: 800,
      milisecondTimer: 800,
      sessionNumber: 2,
    ),
    ActionScreen(
      title: 'Mountain Climber',
      number: 14,
      gifDirectory: "assets/gifs/mountain-climber.gif",
      frameMin: 0,
      frameMax: 4,
      milisecondAnimation: 2500,
      milisecondTimer: 1250,
      sessionNumber: 3,
    ),
    ActionScreen(
      title: 'Cross Arm Crunch',
      number: 15,
      gifDirectory: "assets/gifs/cross-arm-crunches.gif",
      frameMin: 0,
      frameMax: 6,
      milisecondAnimation: 2500,
      milisecondTimer: 2500,
      sessionNumber: 4,
    ),
    ActionScreen(
      title: 'Heel Touch',
      number: 12,
      gifDirectory: "assets/gifs/heel-touch.gif",
      frameMin: 0,
      frameMax: 6,
      milisecondAnimation: 1500,
      milisecondTimer: 1500,
      sessionNumber: 5,
    ),
    ActionScreen(
      title: 'Man Crunches',
      number: 15,
      gifDirectory: "assets/gifs/man-crunches.gif",
      frameMin: 0,
      frameMax: 27,
      milisecondAnimation: 2000,
      milisecondTimer: 2000,
      sessionNumber: 6,
    ),
    ActionScreen(
      title: 'Butt Bridge',
      number: 12,
      gifDirectory: "assets/gifs/butt-bridge.gif",
      frameMin: 0,
      frameMax: 2,
      milisecondAnimation: 2500,
      milisecondTimer: 2500,
      sessionNumber: 7,
    ),
    ActionScreen(
      title: 'Side Crunches',
      number: 16,
      gifDirectory: "assets/gifs/side-crunches.gif",
      frameMin: 0,
      frameMax: 62,
      milisecondAnimation: 2500,
      milisecondTimer: 1250,
      sessionNumber: 8,
    ),
    ActionScreen(
      title: 'Heels To Heaven',
      number: 10,
      gifDirectory: "assets/gifs/heel-to-heaven.gif",
      frameMin: 0,
      frameMax: 32,
      milisecondAnimation: 1500,
      milisecondTimer: 1500,
      sessionNumber: 9,
    ),
    ActionScreen(
      title: 'V-Up',
      number: 10,
      gifDirectory: "assets/gifs/V-Up.gif",
      frameMin: 0,
      frameMax: 10,
      milisecondAnimation: 1500,
      milisecondTimer: 1500,
      sessionNumber: 10,
    ),
    ActionScreen(
      title: 'Plank',
      number: 20,
      gifDirectory: "assets/gifs/plank.gif",
      frameMin: 100,
      frameMax: 180,
      milisecondAnimation: 3000,
      milisecondTimer: 2000,
      sessionNumber: 11,
    ),
    ActionScreen(
      title: 'Skipping Without Rope',
      number: 20,
      gifDirectory: "assets/gifs/jump-rope.gif",
      frameMin: 0,
      frameMax: 9,
      milisecondAnimation: 400,
      milisecondTimer: 800,
      sessionNumber: 12,
    ),
    ActionScreen(
      title: 'Mountain Climber',
      number: 20,
      gifDirectory: "assets/gifs/mountain-climber.gif",
      frameMin: 0,
      frameMax: 4,
      milisecondAnimation: 2500,
      milisecondTimer: 1250,
      sessionNumber: 13,
    ),
    ActionScreen(
      title: 'Cross Arm Crunch',
      number: 15,
      gifDirectory: "assets/gifs/cross-arm-crunches.gif",
      frameMin: 0,
      frameMax: 6,
      milisecondAnimation: 2500,
      milisecondTimer: 2500,
      sessionNumber: 14,
    ),
    ActionScreen(
        title: 'Heel Touch',
        number: 12,
        gifDirectory: "assets/gifs/heel-touch.gif",
        frameMin: 0,
        frameMax: 6,
        milisecondAnimation: 1500,
        milisecondTimer: 1500,
        sessionNumber: 15),
    ActionScreen(
      title: 'Man Crunches',
      number: 15,
      gifDirectory: "assets/gifs/man-crunches.gif",
      frameMin: 0,
      frameMax: 27,
      milisecondAnimation: 2000,
      milisecondTimer: 2000,
      sessionNumber: 16,
    ),
    ActionScreen(
      title: 'Butt Bridge',
      number: 12,
      gifDirectory: "assets/gifs/butt-bridge.gif",
      frameMin: 0,
      frameMax: 2,
      milisecondAnimation: 2500,
      milisecondTimer: 2500,
      sessionNumber: 17,
    ),
    ActionScreen(
      title: 'Side Crunches',
      number: 16,
      gifDirectory: "assets/gifs/side-crunches.gif",
      frameMin: 0,
      frameMax: 62,
      milisecondAnimation: 2500,
      milisecondTimer: 1250,
      sessionNumber: 18,
    ),
    ActionScreen(
      title: 'Heels To Heaven',
      number: 10,
      gifDirectory: "assets/gifs/heel-to-heaven.gif",
      frameMin: 0,
      frameMax: 32,
      milisecondAnimation: 1500,
      milisecondTimer: 1500,
      sessionNumber: 19,
    ),
    ActionScreen(
      title: 'V-Up',
      number: 10,
      gifDirectory: "assets/gifs/V-Up.gif",
      frameMin: 0,
      frameMax: 10,
      milisecondAnimation: 1500,
      milisecondTimer: 1500,
      sessionNumber: 20,
    ),
    ActionScreen(
      title: 'Cobra Stretch',
      number: 15,
      gifDirectory: "assets/gifs/cobra-stretch.gif",
      frameMin: 0,
      frameMax: 7,
      milisecondAnimation: 3000,
      milisecondTimer: 3000,
      sessionNumber: 21,
    ),
    ActionScreen(
      title: 'Lying Twist Stretch',
      number: 10,
      gifDirectory: "assets/gifs/lyingTwistStretch.gif",
      frameMin: 0,
      frameMax: 4,
      milisecondAnimation: 3000,
      milisecondTimer: 3000,
      sessionNumber: 22,
    ),
  ];
}
