import '../screens/actionScreen.dart';

class ArmWorkOutNavigator {
  static List<ActionScreen> list = [
    ActionScreen(
      title: 'Dynamic Stretch',
      number: 15,
      gifDirectory: "assets/gifs/dynamic-stretch.gif",
      frameMin: 0,
      frameMax: 7,
      milisecondAnimation: 2500,
      milisecondTimer: 2500,
      sessionNumber: 1,
    ),
    ActionScreen(
      title: 'Punches',
      number: 20,
      gifDirectory: "assets/gifs/punches.gif",
      frameMin: 0,
      frameMax: 4,
      milisecondAnimation: 2000,
      milisecondTimer: 2000,
      sessionNumber: 2,
    ),
    ActionScreen(
      title: 'Jumping Jacks',
      number: 12,
      gifDirectory: "assets/gifs/jumpingJack.gif",
      frameMin: 0,
      frameMax: 40,
      milisecondAnimation: 1000,
      milisecondTimer: 1000,
      sessionNumber: 3,
    ),
    ActionScreen(
      title: 'Triceps Dips',
      number: 15,
      gifDirectory: "assets/gifs/tricep-dips.gif",
      frameMin: 0,
      frameMax: 5,
      milisecondAnimation: 2000,
      milisecondTimer: 2000,
      sessionNumber: 4,
    ),
    ActionScreen(
      title: 'Wall Push-Ups',
      number: 16,
      gifDirectory: "assets/gifs/wall-push-ups.gif",
      frameMin: 0,
      frameMax: 3,
      milisecondAnimation: 1500,
      milisecondTimer: 1500,
      sessionNumber: 5,
    ),
    ActionScreen(
      title: 'Arm Circles',
      number: 10,
      gifDirectory: "assets/gifs/arm-circle.gif",
      frameMin: 0,
      frameMax: 4,
      milisecondAnimation: 2000,
      milisecondTimer: 2000,
      sessionNumber: 6,
    ),
    ActionScreen(
      title: 'Knee Push-Ups',
      number: 15,
      gifDirectory: "assets/gifs/knee-push-ups.gif",
      frameMin: 0,
      frameMax: 2,
      milisecondAnimation: 2500,
      milisecondTimer: 2500,
      sessionNumber: 7,
    ),
    ActionScreen(
      title: 'Upper Cut',
      number: 14,
      gifDirectory: "assets/gifs/upper-cut.gif",
      frameMin: 0,
      frameMax: 8,
      milisecondAnimation: 3000,
      milisecondTimer: 3000,
      sessionNumber: 8,
    ),
    ActionScreen(
      title: 'Up & Down Plank',
      number: 12,
      gifDirectory: "assets/gifs/up-down-plank.gif",
      frameMin: 0,
      frameMax: 6,
      milisecondAnimation: 4000,
      milisecondTimer: 4000,
      sessionNumber: 9,
    ),
    ActionScreen(
      title: 'Chest Press Pulse',
      number: 15,
      gifDirectory: "assets/gifs/chest-press-pulse.gif",
      frameMin: 0,
      frameMax: 2,
      milisecondAnimation: 2000,
      milisecondTimer: 2000,
      sessionNumber: 10,
    ),
    ActionScreen(
      title: 'Arm Scissors',
      number: 10,
      gifDirectory: "assets/gifs/arm-scissors.gif",
      frameMin: 0,
      frameMax: 4,
      milisecondAnimation: 3500,
      milisecondTimer: 3500,
      sessionNumber: 11,
    ),
    ActionScreen(
      title: 'Triceps Dips',
      number: 15,
      gifDirectory: "assets/gifs/tricep-dips.gif",
      frameMin: 0,
      frameMax: 5,
      milisecondAnimation: 2000,
      milisecondTimer: 2000,
      sessionNumber: 12,
    ),
    ActionScreen(
      title: 'Arm Circles',
      number: 10,
      gifDirectory: "assets/gifs/arm-circle.gif",
      frameMin: 0,
      frameMax: 4,
      milisecondAnimation: 2000,
      milisecondTimer: 2000,
      sessionNumber: 13,
    ),
    ActionScreen(
      title: 'Knee Push-Ups',
      number: 15,
      gifDirectory: "assets/gifs/knee-push-ups.gif",
      frameMin: 0,
      frameMax: 2,
      milisecondAnimation: 2500,
      milisecondTimer: 2500,
      sessionNumber: 14,
    ),
    ActionScreen(
      title: 'Upper Cut',
      number: 14,
      gifDirectory: "assets/gifs/upper-cut.gif",
      frameMin: 0,
      frameMax: 8,
      milisecondAnimation: 3000,
      milisecondTimer: 3000,
      sessionNumber: 15,
    ),
    ActionScreen(
      title: 'Up & Down Plank',
      number: 12,
      gifDirectory: "assets/gifs/up-down-plank.gif",
      frameMin: 0,
      frameMax: 6,
      milisecondAnimation: 4000,
      milisecondTimer: 4000,
      sessionNumber: 16,
    ),
    ActionScreen(
      title: 'Chest Press Pulse',
      number: 15,
      gifDirectory: "assets/gifs/chest-press-pulse.gif",
      frameMin: 0,
      frameMax: 2,
      milisecondAnimation: 2000,
      milisecondTimer: 2000,
      sessionNumber: 17,
    ),
    ActionScreen(
      title: 'Triceps Stretch',
      number: 14,
      gifDirectory: "assets/gifs/tricep-stretch.gif",
      frameMin: 0,
      frameMax: 5,
      milisecondAnimation: 3000,
      milisecondTimer: 3000,
      sessionNumber: 18,
    ),
    ActionScreen(
      title: 'Biceps Stretch',
      number: 10,
      gifDirectory: "assets/gifs/bicep-stretch.gif",
      frameMin: 0,
      frameMax: 5,
      milisecondAnimation: 3000,
      milisecondTimer: 3000,
      sessionNumber: 19,
    )
  ];
}
