import '../screens/actionScreen.dart';

class ButtBeginnerNavigator {
  static List<ActionScreen> list = [
    ActionScreen(
      title: 'High Stepping',
      number: 20,
      gifDirectory: "assets/gifs/highStepping.gif",
      frameMin: 0,
      frameMax: 17,
      milisecondAnimation: 800,
      milisecondTimer: 800,
      sessionNumber: 1,
    ), 
    ActionScreen(
      title: 'Butt Kicks',
      number: 20,
      gifDirectory: "assets/gifs/butt-kicks.gif",
      frameMin: 0,
      frameMax: 44,
      milisecondAnimation: 3200,
      milisecondTimer: 1500,
      sessionNumber: 2,
    ),
    ActionScreen(
      title: 'Squarts',
      number: 10,
      gifDirectory: "assets/gifs/squats-min.gif",
      frameMin: 0,
      frameMax: 2,
      milisecondAnimation: 2000,
      milisecondTimer: 2000,
      sessionNumber: 3,
    ),
    ActionScreen(
      title: 'Standing Glute Kickbacks',
      number: 15,
      gifDirectory: "assets/gifs/glute-kick-backs.gif",
      frameMin: 0,
      frameMax: 16,
      milisecondAnimation: 2000,
      milisecondTimer: 2000,
      sessionNumber: 4,
    ),
    ActionScreen(
      title: 'Butt Bridge',
      number: 12,
      gifDirectory: "assets/gifs/butt-bridge.gif",
      frameMin: 0,
      frameMax: 2,
      milisecondAnimation: 2500,
      milisecondTimer: 2500,
      sessionNumber: 5,
    ),
    ActionScreen(
      title: 'Mountain Climber',
      number: 15,
      gifDirectory: "assets/gifs/mountain-climber.gif",
      frameMin: 0,
      frameMax: 4,
      milisecondAnimation: 2500,
      milisecondTimer: 1250,
      sessionNumber: 6,
    ),
    ActionScreen(
      title: 'Donkey Kick Right',
      number: 10,
      gifDirectory: "assets/gifs/donkey-kick-right.gif",
      frameMin: 0,
      frameMax: 56,
      milisecondAnimation: 3000,
      milisecondTimer: 3000,
      sessionNumber: 7,
    ),
    ActionScreen(
      title: 'Donkey Kick Left',
      number: 10,
      gifDirectory: "assets/gifs/donkey-kick-left.gif",
      frameMin: 0,
      frameMax: 20,
      milisecondAnimation: 3000,
      milisecondTimer: 3000,
      sessionNumber: 8,
    ),
    ActionScreen(
      title: 'Jumping Lunges',
      number: 14,
      gifDirectory: "assets/gifs/jump-lunges.gif",
      frameMin: 0,
      frameMax: 4,
      milisecondAnimation: 2500,
      milisecondTimer: 1250,
      sessionNumber: 9,
    ),
    ActionScreen(
      title: 'Bottom Leg Lift',
      number: 14,
      gifDirectory: "assets/gifs/bottom-leg-lift.gif",
      frameMin: 0,
      frameMax: 10,
      milisecondAnimation: 4000,
      milisecondTimer: 2000,
      sessionNumber: 10,
    ),
    ActionScreen(
      title: 'Squarts',
      number: 10,
      gifDirectory: "assets/gifs/squats-min.gif",
      frameMin: 0,
      frameMax: 2,
      milisecondAnimation: 2000,
      milisecondTimer: 2000,
      sessionNumber: 11,
    ),
    ActionScreen(
      title: 'Fire Hydrant Right',
      number: 10,
      gifDirectory: "assets/gifs/fire-hydrant-right.gif",
      frameMin: 0,
      frameMax: 67,
      milisecondAnimation: 2000,
      milisecondTimer: 2000,
      sessionNumber: 12,
    ),
    ActionScreen(
      title: 'Fire Hydrant Left',
      number: 10,
      gifDirectory: "assets/gifs/fire-hydrant-left.gif",
      frameMin: 0,
      frameMax: 67,
      milisecondAnimation: 2000,
      milisecondTimer: 2000,
      sessionNumber: 13,
    ),
    ActionScreen(
      title: 'Skipping Without Rope',
      number: 14,
      gifDirectory: "assets/gifs/jump-rope.gif",
      frameMin: 0,
      frameMax: 9,
      milisecondAnimation: 400,
      milisecondTimer: 800,
      sessionNumber: 14,
    ),
    ActionScreen(
        title: 'Butt Kicks',
        number: 16,
        gifDirectory: "assets/gifs/butt-kicks.gif",
        frameMin: 0,
        frameMax: 44,
        milisecondAnimation: 3200,
        milisecondTimer: 1500,
        sessionNumber: 15),
    ActionScreen(
      title: 'Standing Glute Kickbacks',
      number: 15,
      gifDirectory: "assets/gifs/glute-kick-backs.gif",
      frameMin: 0,
      frameMax: 16,
      milisecondAnimation: 2500,
      milisecondTimer: 2500,
      sessionNumber: 16,
    ),
  ];
}
