import '../screens/actionScreen.dart';

class ButtAdvanceNavigator {
  static List<ActionScreen> list = [
    ActionScreen(
      title: 'High Stepping',
      number: 16,
      gifDirectory: "assets/gifs/highStepping.gif",
      frameMin: 0,
      frameMax: 17,
      milisecondAnimation: 800,
      milisecondTimer: 800,
      sessionNumber: 1,
    ),
    ActionScreen(
      title: 'Butt Kicks',
      number: 14,
      gifDirectory: "assets/gifs/butt-kicks.gif",
      frameMin: 0,
      frameMax: 44,
      milisecondAnimation: 3200,
      milisecondTimer: 1500,
      sessionNumber: 2,
    ),
    ActionScreen(
      title: 'Squarts',
      number: 10,
      gifDirectory: "assets/gifs/squats-min.gif",
      frameMin: 0,
      frameMax: 2,
      milisecondAnimation: 2000,
      milisecondTimer: 2000,
      sessionNumber: 3,
    ),
    ActionScreen(
      title: 'Standing Glute Kickbacks',
      number: 15,
      gifDirectory: "assets/gifs/glute-kick-backs.gif",
      frameMin: 0,
      frameMax: 16,
      milisecondAnimation: 2000,
      milisecondTimer: 2000,
      sessionNumber: 4,
    ),
    ActionScreen(
      title: 'Donkey Kick Right',
      number: 10,
      gifDirectory: "assets/gifs/donkey-kick-right.gif",
      frameMin: 0,
      frameMax: 56,
      milisecondAnimation: 3000,
      milisecondTimer: 3000,
      sessionNumber: 5,
    ),
    ActionScreen(
      title: 'Donkey Kick Left',
      number: 10,
      gifDirectory: "assets/gifs/donkey-kick-left.gif",
      frameMin: 0,
      frameMax: 20,
      milisecondAnimation: 3000,
      milisecondTimer: 3000,
      sessionNumber: 6,
    ),
    ActionScreen(
      title: 'Butt Bridge',
      number: 12,
      gifDirectory: "assets/gifs/butt-bridge.gif",
      frameMin: 0,
      frameMax: 2,
      milisecondAnimation: 1500,
      milisecondTimer: 1500,
      sessionNumber: 7,
    ),
    ActionScreen(
      title: 'Jumping Lunges',
      number: 14,
      gifDirectory: "assets/gifs/jump-lunges.gif",
      frameMin: 0,
      frameMax: 4,
      milisecondAnimation: 2500,
      milisecondTimer: 1250,
      sessionNumber: 8,
    ),
    ActionScreen(
      title: 'Mountain Climber',
      number: 15,
      gifDirectory: "assets/gifs/mountain-climber.gif",
      frameMin: 0,
      frameMax: 4,
      milisecondAnimation: 2500,
      milisecondTimer: 1250,
      sessionNumber: 9,
    ),
    ActionScreen(
      title: 'Curtsy Lunges',
      number: 16,
      gifDirectory: "assets/gifs/curtsy-lunges.gif",
      frameMin: 0,
      frameMax: 8,
      milisecondAnimation: 4000,
      milisecondTimer: 2000, 
      sessionNumber: 10,
    ),
    ActionScreen(
      title: 'Flutter Kicks',
      number: 20,
      gifDirectory: "assets/gifs/flutter-kicks.gif",
      frameMin: 5,
      frameMax: 90,
      milisecondAnimation: 3000,
      milisecondTimer: 1000,
      sessionNumber: 11,
    ),
    ActionScreen(
      title: 'Sumo Squat',
      number: 15,
      gifDirectory: "assets/gifs/sumo-squats.gif",
      frameMin: 0,
      frameMax: 62,
      milisecondAnimation: 2500,
      milisecondTimer: 2500,
      sessionNumber: 12,
    ),
    ActionScreen(
      title: 'Hip Bridge & Leg Lift 1',
      number: 10,
      gifDirectory: "assets/gifs/hip-bridge&leg-lift.gif",
      frameMin: 0,
      frameMax: 19,
      milisecondAnimation: 2000,
      milisecondTimer: 2000,
      sessionNumber: 13,
    ),
    ActionScreen(
      title: 'Hip Bridge & Leg Lift 2',
      number: 10,
      gifDirectory: "assets/gifs/hip-bridge&leg-lift2.gif",
      frameMin: 0,
      frameMax: 18,
      milisecondAnimation: 2000,
      milisecondTimer: 2000,
      sessionNumber: 14,
    ),
    ActionScreen(
        title: 'Squarts',
        number: 10,
        gifDirectory: "assets/gifs/squats-min.gif",
        frameMin: 0,
        frameMax: 2,
        milisecondAnimation: 2000,
        milisecondTimer: 2000,
        sessionNumber: 15),
    ActionScreen(
      title: 'Butt Bridge',
      number: 12,
      gifDirectory: "assets/gifs/butt-bridge.gif",
      frameMin: 0,
      frameMax: 2,
      milisecondAnimation: 2500,
      milisecondTimer: 2500,
      sessionNumber: 16,
    ),
    ActionScreen(
      title: 'Curtsy Lunges',
      number: 16,
      gifDirectory: "assets/gifs/curtsy-lunges.gif",
      frameMin: 0,
      frameMax: 8,
      milisecondAnimation: 4000,
      milisecondTimer: 2000,
      sessionNumber: 17,
    ),
    ActionScreen(
      title: 'Mountain Climber',
      number: 14,
      gifDirectory: "assets/gifs/mountain-climber.gif",
      frameMin: 0,
      frameMax: 4,
      milisecondAnimation: 2500,
      milisecondTimer: 1250,
      sessionNumber: 18,
    ),
    ActionScreen(
      title: 'Jumping Lunges',
      number: 14,
      gifDirectory: "assets/gifs/jump-lunges.gif",
      frameMin: 0,
      frameMax: 4,
      milisecondAnimation: 2500,
      milisecondTimer: 1250,
      sessionNumber: 19,
    ),
    ActionScreen(
      title: 'Flutter Kicks',
      number: 20,
      gifDirectory: "assets/gifs/flutter-kicks.gif",
      frameMin: 5,
      frameMax: 90,
      milisecondAnimation: 3000,
      milisecondTimer: 1000,
      sessionNumber: 20,
    ),
    ActionScreen(
      title: 'Sumo Squat',
      number: 15,
      gifDirectory: "assets/gifs/sumo-squats.gif",
      frameMin: 0,
      frameMax: 62,
      milisecondAnimation: 2500,
      milisecondTimer: 2500,
      sessionNumber: 21,
    ),
    ActionScreen(
      title: 'Hip Bridge & Leg Lift 1',
      number: 10,
      gifDirectory: "assets/gifs/hip-bridge&leg-lift.gif",
      frameMin: 0,
      frameMax: 19,
      milisecondAnimation: 2000,
      milisecondTimer: 2000,
      sessionNumber: 22,
    ),
    ActionScreen(
      title: 'Hip Bridge & Leg Lift 2',
      number: 10,
      gifDirectory: "assets/gifs/hip-bridge&leg-lift2.gif",
      frameMin: 0,
      frameMax: 18,
      milisecondAnimation: 2000,
      milisecondTimer: 2000,
      sessionNumber: 23,
    ),
    ActionScreen(
      title: 'Kneeling Lungh Stretch',
      number: 13,
      gifDirectory: "assets/gifs/kneeling-lungh-stretch.gif",
      frameMin: 0,
      frameMax: 2,
      milisecondAnimation: 3000,
      milisecondTimer: 3000,
      sessionNumber: 24,
    ),
  ];
}
