import '../screens/actionScreen.dart';

class FullBodyNavigator {
  static List<ActionScreen> list = [
    ActionScreen(
      title: 'High Stepping',
      number: 20,
      gifDirectory: "assets/gifs/highStepping.gif",
      frameMin: 0,
      frameMax: 17,
      milisecondAnimation: 1000,
      milisecondTimer: 1000,
      sessionNumber: 1,
    ),
    ActionScreen(
      title: 'Side Hop',
      number: 15,
      gifDirectory: "assets/gifs/side-hop-min.gif",
      frameMin: 0,
      frameMax: 30,
      milisecondAnimation: 1800,
      milisecondTimer: 1800,
      sessionNumber: 2,
    ),
    ActionScreen(
      title: 'Squats',
      number: 15,
      gifDirectory: "assets/gifs/squats-min.gif",
      frameMin: 0,
      frameMax: 2,
      milisecondAnimation: 2000,
      milisecondTimer: 2000,
      sessionNumber: 3,
    ),
    ActionScreen(
      title: 'Wall Push-Ups',
      number: 12,
      gifDirectory: "assets/gifs/wall-push-ups.gif",
      frameMin: 0,
      frameMax: 3,
      milisecondAnimation: 1500,
      milisecondTimer: 1500,
      sessionNumber: 4,
    ),
    ActionScreen(
      title: 'Butt Bridge',
      number: 12,
      gifDirectory: "assets/gifs/butt-bridge.gif",
      frameMin: 0,
      frameMax: 2,
      milisecondAnimation: 2500,
      milisecondTimer: 2500,
      sessionNumber: 5,
    ),
    ActionScreen(
      title: 'Fire Hydrant Right',
      number: 10,
      gifDirectory: "assets/gifs/fire-hydrant-right.gif",
      frameMin: 0,
      frameMax: 67,
      milisecondAnimation: 2000,
      milisecondTimer: 2000,
      sessionNumber: 6,
    ),
    ActionScreen(
      title: 'Fire Hydrant Left',
      number: 10,
      gifDirectory: "assets/gifs/fire-hydrant-left.gif",
      frameMin: 0,
      frameMax: 67,
      milisecondAnimation: 2000,
      milisecondTimer: 2000,
      sessionNumber: 7,
    ),
    ActionScreen(
      title: 'Plank',
      number: 20,
      gifDirectory: "assets/gifs/plank.gif",
      frameMin: 100,
      frameMax: 180,
      milisecondAnimation: 3000,
      milisecondTimer: 2000,
      sessionNumber: 8,
    ),
    ActionScreen(
      title: 'Butt Kicks',
      number: 15,
      gifDirectory: "assets/gifs/butt-kicks.gif",
      frameMin: 0,
      frameMax: 44,
      milisecondAnimation: 3200,
      milisecondTimer: 1500,
      sessionNumber: 9,
    ),
    ActionScreen(
      title: 'Squarts',
      number: 10,
      gifDirectory: "assets/gifs/squats-min.gif",
      frameMin: 0,
      frameMax: 2,
      milisecondAnimation: 2000,
      milisecondTimer: 2000,
      sessionNumber: 10,
    ),
    ActionScreen(
      title: 'Wall Push-Ups',
      number: 12,
      gifDirectory: "assets/gifs/wall-push-ups.gif",
      frameMin: 0,
      frameMax: 3,
      milisecondAnimation: 2000,
      milisecondTimer: 2000,
      sessionNumber: 11,
    ),
    ActionScreen(
      title: 'Butt Bridge',
      number: 12,
      gifDirectory: "assets/gifs/butt-bridge.gif",
      frameMin: 0,
      frameMax: 2,
      milisecondAnimation: 2500,
      milisecondTimer: 2500,
      sessionNumber: 12,
    ),
    ActionScreen(
      title: 'Cobra Stretch',
      number: 15,
      gifDirectory: "assets/gifs/cobra-stretch.gif",
      frameMin: 0,
      frameMax: 7,
      milisecondAnimation: 3000,
      milisecondTimer: 3000,
      sessionNumber: 13,
    ),
    ActionScreen(
      title: "Child's Pose",
      number: 8,
      gifDirectory: "assets/gifs/child-pose-min.gif",
      frameMin: 0,
      frameMax: 5,
      milisecondAnimation: 5000,
      milisecondTimer: 5000,
      sessionNumber: 14,
    ),
    ActionScreen(
      title: 'High Stepping',
      number: 12,
      gifDirectory: "assets/gifs/highStepping.gif",
      frameMin: 0,
      frameMax: 17,
      milisecondAnimation: 800,
      milisecondTimer: 800,
      sessionNumber: 15,
    ),
    ActionScreen(
      title: 'Knee To Chest Stretch',
      number: 10,
      gifDirectory: "assets/gifs/knee-to-chest.gif",
      frameMin: 0,
      frameMax: 11, 
      milisecondAnimation: 2200,
      milisecondTimer: 2200,
      sessionNumber: 16,
    )
  ];
}
