import '../screens/actionScreen.dart';

class LowerBackNavigator {
  static List<ActionScreen> list = [
    ActionScreen(
      title: 'Forward Bend',
      number: 8,
      gifDirectory: "assets/gifs/stand-and-reach.gif",
      frameMin: 0,
      frameMax: 6,
      milisecondAnimation: 3000,
      milisecondTimer: 3000,
      sessionNumber: 1,
    ),
    ActionScreen(
      title: 'Butt Bridge',
      number: 10,
      gifDirectory: "assets/gifs/butt-bridge.gif",
      frameMin: 0,
      frameMax: 2,
      milisecondAnimation: 2500,
      milisecondTimer: 2500,
      sessionNumber: 2,
    ),
    ActionScreen(
      title: "Child's Pose",
      number: 6,
      gifDirectory: "assets/gifs/child-pose-min.gif",
      frameMin: 0,
      frameMax: 5,
      milisecondAnimation: 5000,
      milisecondTimer: 5000,
      sessionNumber: 3,
    ),
    ActionScreen(
      title: 'Cobra Stretch',
      number: 8,
      gifDirectory: "assets/gifs/cobra-stretch.gif",
      frameMin: 0,
      frameMax: 7,
      milisecondAnimation: 3000,
      milisecondTimer: 3000,
      sessionNumber: 4,
    ),
    ActionScreen(
      title: 'Cross Arm Crunch',
      number: 8,
      gifDirectory: "assets/gifs/cross-arm-crunches.gif",
      frameMin: 0,
      frameMax: 6,
      milisecondAnimation: 2500,
      milisecondTimer: 2500,
      sessionNumber: 5,
    ),
    ActionScreen(
      title: 'Frog Position',
      number: 10,
      gifDirectory: "assets/gifs/frog-position.gif",
      frameMin: 0,
      frameMax: 29,
      milisecondAnimation: 1700,
      milisecondTimer: 1700,
      sessionNumber: 6,
    ),
    ActionScreen(
      title: 'Plank',
      number: 15,
      gifDirectory: "assets/gifs/plank.gif",
      frameMin: 100,
      frameMax: 180,
      milisecondAnimation: 3000,
      milisecondTimer: 2000,
      sessionNumber: 7,
    ),
    ActionScreen(
      title: 'Hip Bridge & Leg Lift 1',
      number: 10,
      gifDirectory: "assets/gifs/hip-bridge&leg-lift.gif",
      frameMin: 0,
      frameMax: 19,
      milisecondAnimation: 2000,
      milisecondTimer: 2000,
      sessionNumber: 8,
    ),
    ActionScreen(
      title: 'Hip Bridge & Leg Lift 2',
      number: 10,
      gifDirectory: "assets/gifs/hip-bridge&leg-lift2.gif",
      frameMin: 0,
      frameMax: 18,
      milisecondAnimation: 2000,
      milisecondTimer: 2000,
      sessionNumber: 9,
    ),
    ActionScreen(
      title: 'Lying Twist Stretch',
      number: 10,
      gifDirectory: "assets/gifs/lyingTwistStretch.gif",
      frameMin: 0,
      frameMax: 4,
      milisecondAnimation: 3000,
      milisecondTimer: 3000,
      sessionNumber: 10,
    ),
  ];
}
