import '../screens/actionScreen.dart';

class NeckShoulderNavigator {
  static List<ActionScreen> list = [
    ActionScreen(
      title: 'Dynamic Stretch',
      number: 15,
      gifDirectory: "assets/gifs/dynamic-stretch.gif",
      frameMin: 0,
      frameMax: 7,
      milisecondAnimation: 2500,
      milisecondTimer: 2500,
      sessionNumber: 1,
    ),
    ActionScreen(
      title: 'Shoulder Stretch Right',
      number: 6,
      gifDirectory: "assets/gifs/shoulder-stretch-right.gif",
      frameMin: 0,
      frameMax: 8,
      milisecondAnimation: 3000,
      milisecondTimer: 3000,
      sessionNumber: 2,
    ),
    ActionScreen(
      title: 'Shoulder Stretch Left',
      number: 6,
      gifDirectory: "assets/gifs/shoulder-stretch-left.gif",
      frameMin: 0,
      frameMax: 8,
      milisecondAnimation: 3000,
      milisecondTimer: 3000,
      sessionNumber: 3,
    ),
    ActionScreen(
      title: 'Triceps Stretch',
      number: 14,
      gifDirectory: "assets/gifs/tricep-stretch.gif",
      frameMin: 0,
      frameMax: 5,
      milisecondAnimation: 3000,
      milisecondTimer: 3000,
      sessionNumber: 4,
    ),
    ActionScreen(
      title: 'Biceps Stretch',
      number: 10,
      gifDirectory: "assets/gifs/bicep-stretch.gif",
      frameMin: 0,
      frameMax: 5,
      milisecondAnimation: 3000,
      milisecondTimer: 3000,
      sessionNumber: 5,
    ),
    ActionScreen(
      title: 'Neck Stretch',
      number: 8,
      gifDirectory: "assets/gifs/neck-stretch.gif",
      frameMin: 0,
      frameMax: 8,
      milisecondAnimation: 3000,
      milisecondTimer: 3000,
      sessionNumber: 6,
    ),
    ActionScreen(
      title: 'Roll & Shrug',
      number: 8,
      gifDirectory: "assets/gifs/rolls-and-shrugs.gif",
      frameMin: 0,
      frameMax: 4,
      milisecondAnimation: 2000,
      milisecondTimer: 2000,
      sessionNumber: 7,
    ),
    ActionScreen(
      title: 'Arm Circles',
      number: 10,
      gifDirectory: "assets/gifs/arm-circle.gif",
      frameMin: 0,
      frameMax: 4,
      milisecondAnimation: 2000,
      milisecondTimer: 2000,
      sessionNumber: 8,
    ),
    ActionScreen(
      title: 'Triceps Dips',
      number: 15,
      gifDirectory: "assets/gifs/tricep-dips.gif",
      frameMin: 0,
      frameMax: 5,
      milisecondAnimation: 2000,
      milisecondTimer: 2000,
      sessionNumber: 9,
    ),
    ActionScreen(
      title: 'Chest Press Pulse',
      number: 15,
      gifDirectory: "assets/gifs/chest-press-pulse.gif",
      frameMin: 0,
      frameMax: 2,
      milisecondAnimation: 2000,
      milisecondTimer: 2000,
      sessionNumber: 10,
    ),
  ];
}
