import '../screens/actionScreen.dart';

class ThighBeginnerNavigator {
  static List<ActionScreen> list = [
    ActionScreen(
      title: 'High Stepping',
      number: 14,
      gifDirectory: "assets/gifs/highStepping.gif",
      frameMin: 0,
      frameMax: 17,
      milisecondAnimation: 1000,
      milisecondTimer: 1000,
      sessionNumber: 1,
    ),
    ActionScreen(
      title: 'Jumping Jacks',
      number: 12,
      gifDirectory: "assets/gifs/jumpingJack.gif",
      frameMin: 0,
      frameMax: 40,
      milisecondAnimation: 1000,
      milisecondTimer: 1000,
      sessionNumber: 2,
    ),
    ActionScreen(
      title: 'Squarts',
      number: 10,
      gifDirectory: "assets/gifs/squats-min.gif",
      frameMin: 0,
      frameMax: 2,
      milisecondAnimation: 2000,
      milisecondTimer: 2000,
      sessionNumber: 3,
    ),
    ActionScreen(
      title: 'Donkey Kick Right',
      number: 10,
      gifDirectory: "assets/gifs/donkey-kick-right.gif",
      frameMin: 0,
      frameMax: 56,
      milisecondAnimation: 3000,
      milisecondTimer: 3000,
      sessionNumber: 4,
    ),
    ActionScreen(
      title: 'Donkey Kick Left',
      number: 10,
      gifDirectory: "assets/gifs/donkey-kick-left.gif",
      frameMin: 0,
      frameMax: 20,
      milisecondAnimation: 3000,
      milisecondTimer: 3000,
      sessionNumber: 5,
    ),
    ActionScreen(
      title: 'Curtsy Lunges',
      number: 16,
      gifDirectory: "assets/gifs/curtsy-lunges.gif",
      frameMin: 0,
      frameMax: 8,
      milisecondAnimation: 4000,
      milisecondTimer: 2000,
      sessionNumber: 6,
    ),
    ActionScreen(
      title: 'Modified Burpees',
      number: 13,
      gifDirectory: "assets/gifs/modified-burpees.gif",
      frameMin: 0,
      frameMax: 109,
      milisecondAnimation: 3000,
      milisecondTimer: 3000,
      sessionNumber: 7,
    ),
    ActionScreen(
      title: 'Squarts',
      number: 10,
      gifDirectory: "assets/gifs/squats-min.gif",
      frameMin: 0,
      frameMax: 2,
      milisecondAnimation: 2000,
      milisecondTimer: 2000,
      sessionNumber: 8,
    ),
    ActionScreen(
      title: 'Frog Position',
      number: 10,
      gifDirectory: "assets/gifs/frog-position.gif",
      frameMin: 0,
      frameMax: 29,
      milisecondAnimation: 1700,
      milisecondTimer: 1700,
      sessionNumber: 9,
    ),
    ActionScreen(
      title: 'Sumo Squat',
      number: 15,
      gifDirectory: "assets/gifs/sumo-squats.gif",
      frameMin: 0,
      frameMax: 62,
      milisecondAnimation: 2500,
      milisecondTimer: 2500,
      sessionNumber: 10,
    ),
    ActionScreen(
      title: 'Fire Hydrant Right',
      number: 10,
      gifDirectory: "assets/gifs/fire-hydrant-right.gif",
      frameMin: 0,
      frameMax: 67,
      milisecondAnimation: 2000,
      milisecondTimer: 2000,
      sessionNumber: 11,
    ),
    ActionScreen(
      title: 'Fire Hydrant Left',
      number: 10,
      gifDirectory: "assets/gifs/fire-hydrant-left.gif",
      frameMin: 0,
      frameMax: 67,
      milisecondAnimation: 2000,
      milisecondTimer: 2000,
      sessionNumber: 12,
    ),
    ActionScreen(
      title: 'Jumping Lunges',
      number: 14,
      gifDirectory: "assets/gifs/jump-lunges.gif",
      frameMin: 0,
      frameMax: 4,
      milisecondAnimation: 2500,
      milisecondTimer: 1250,
      sessionNumber: 13,
    ),
    ActionScreen(
      title: 'Mountain Climber',
      number: 14,
      gifDirectory: "assets/gifs/mountain-climber.gif",
      frameMin: 0,
      frameMax: 4,
      milisecondAnimation: 2500,
      milisecondTimer: 1250,
      sessionNumber: 14,
    ),
    ActionScreen(
      title: 'Curtsy Lunges',
      number: 16,
      gifDirectory: "assets/gifs/curtsy-lunges.gif",
      frameMin: 0,
      frameMax: 8,
      milisecondAnimation: 4000,
      milisecondTimer: 2000,
      sessionNumber: 15
    ),
    ActionScreen(
      title: 'Butterfly Stretch',
      number: 10,
      gifDirectory: "assets/gifs/butterfly-stretch.gif",
      frameMin: 0,
      frameMax: 6,
      milisecondAnimation: 2500,
      milisecondTimer: 2500,
      sessionNumber: 16
    ),
  ];
}
