import '../screens/actionScreen.dart';

class ThighAdvanceNavigator {
  static List<ActionScreen> list = [
    ActionScreen(
      title: 'High Stepping', 
      number: 15,
      gifDirectory: "assets/gifs/highStepping.gif",
      frameMin: 0,
      frameMax: 17,
      milisecondAnimation: 1000,
      milisecondTimer: 1000,
      sessionNumber: 1,
    ),
    ActionScreen(
      title: 'Modified Burpees',
      number: 13,
      gifDirectory: "assets/gifs/modified-burpees.gif",
      frameMin: 0,
      frameMax: 109,
      milisecondAnimation: 3000,
      milisecondTimer: 3000,
      sessionNumber: 2,
    ),
    ActionScreen(
      title: 'Squarts',
      number: 10,
      gifDirectory: "assets/gifs/squats-min.gif",
      frameMin: 0,
      frameMax: 2,
      milisecondAnimation: 2000,
      milisecondTimer: 2000,
      sessionNumber: 3,
    ),
    ActionScreen(
      title: 'Side Hop',
      number: 15,
      gifDirectory: "assets/gifs/side-hop-min.gif",
      frameMin: 0,
      frameMax: 30,
      milisecondAnimation: 1500,
      milisecondTimer: 1500,
      sessionNumber: 4,
    ),
    ActionScreen(
      title: 'Bottom Leg Lift',
      number: 14,
      gifDirectory: "assets/gifs/bottom-leg-lift.gif",
      frameMin: 0,
      frameMax: 10,
      milisecondAnimation: 4000,
      milisecondTimer: 2000,
      sessionNumber: 5,
    ),
    ActionScreen(
      title: 'Jumping Squats',
      number: 10,
      gifDirectory: "assets/gifs/jumping-squats.gif",
      frameMin: 0,
      frameMax: 31,
      milisecondAnimation: 1500,
      milisecondTimer: 1500,
      sessionNumber: 6,
    ),
    ActionScreen(
      title: 'Side Leg Circle Right',
      number: 10,
      gifDirectory: "assets/gifs/side-leg-circle1.gif",
      frameMin: 0,
      frameMax: 4,
      milisecondAnimation: 3000,
      milisecondTimer: 3000,
      sessionNumber: 7,
    ),
    ActionScreen(
      title: 'Side Leg Circle Left',
      number: 10,
      gifDirectory: "assets/gifs/side-leg-circle2.gif",
      frameMin: 0,
      frameMax: 4,
      milisecondAnimation: 3000,
      milisecondTimer: 3000,
      sessionNumber: 8,
    ),
    ActionScreen(
      title: 'Glute Kick Back',
      number: 15,
      gifDirectory: "assets/gifs/glute-kick-backs.gif",
      frameMin: 0,
      frameMax: 16,
      milisecondAnimation: 2500,
      milisecondTimer: 2500,
      sessionNumber: 9,
    ),
    ActionScreen(
      title: 'Modified Burpees',
      number: 13,
      gifDirectory: "assets/gifs/modified-burpees.gif",
      frameMin: 0,
      frameMax: 109,
      milisecondAnimation: 3000,
      milisecondTimer: 3000,
      sessionNumber: 10,
    ),
    ActionScreen(
      title: 'Squarts',
      number: 14,
      gifDirectory: "assets/gifs/squats-min.gif",
      frameMin: 0,
      frameMax: 2,
      milisecondAnimation: 2000,
      milisecondTimer: 2000,
      sessionNumber: 11,
    ),
    ActionScreen(
      title: 'Curtsy Lunges',
      number: 16,
      gifDirectory: "assets/gifs/curtsy-lunges.gif",
      frameMin: 0,
      frameMax: 8,
      milisecondAnimation: 4000,
      milisecondTimer: 2000,
      sessionNumber: 12,
    ),
    ActionScreen(
      title: 'Bottom Leg Lift',
      number: 14,
      gifDirectory: "assets/gifs/bottom-leg-lift.gif",
      frameMin: 0,
      frameMax: 10,
      milisecondAnimation: 4000,
      milisecondTimer: 2000,
      sessionNumber: 13,
    ),
    ActionScreen(
      title: 'Sumo Squat',
      number: 15,
      gifDirectory: "assets/gifs/sumo-squats.gif",
      frameMin: 0,
      frameMax: 62,
      milisecondAnimation: 2500,
      milisecondTimer: 2500,
      sessionNumber: 14,
    ),
    ActionScreen(
        title: 'Glute Kick Back',
        number: 15,
        gifDirectory: "assets/gifs/glute-kick-backs.gif",
        frameMin: 0,
        frameMax: 16,
        milisecondAnimation: 2500,
        milisecondTimer: 2500,
        sessionNumber: 15),
    ActionScreen(
      title: 'Wall Sit',
      number: 13,
      gifDirectory: "assets/gifs/wall-sit.gif",
      frameMin: 0,
      frameMax: 6,
      milisecondAnimation: 3000,
      milisecondTimer: 3000,
      sessionNumber: 16,
    ),
    ActionScreen(
      title: 'Quad Stretch',
      number: 10,
      gifDirectory: "assets/gifs/quad-stretch.gif",
      frameMin: 0,
      frameMax: 14,
      milisecondAnimation: 5000,
      milisecondTimer: 5000,
      sessionNumber: 17,
    ),
    ActionScreen(
      title: 'Hamstring Stretch Right',
      number: 20,
      gifDirectory: "assets/gifs/hamstring-stretch-right.gif",
      frameMin: 0,
      frameMax: 6,
      milisecondAnimation: 3000,
      milisecondTimer: 3000,
      sessionNumber: 18,
    ),
    ActionScreen(
      title: 'Hamstring Stretch Left',
      number: 20,
      gifDirectory: "assets/gifs/hamstring-stretch-left.gif",
      frameMin: 0,
      frameMax: 6,
      milisecondAnimation: 3000,
      milisecondTimer: 3000,
      sessionNumber: 19,
    ),
    ActionScreen(
      title: 'Runner Stretch Right',
      number: 8,
      gifDirectory: "assets/gifs/runner-stretch-right.gif",
      frameMin: 0,
      frameMax: 7,
      milisecondAnimation: 4000,
      milisecondTimer: 4000,
      sessionNumber: 20,
    ),
    ActionScreen(
      title: 'Runner Stretch Left',
      number: 8,
      gifDirectory: "assets/gifs/runner-stretch-left.gif",
      frameMin: 0,
      frameMax: 7,
      milisecondAnimation: 4000,
      milisecondTimer: 4000,
      sessionNumber: 21,
    ),
    ActionScreen(
      title: 'Butterfly Stretch',
      number: 10,
      gifDirectory: "assets/gifs/butterfly-stretch.gif",
      frameMin: 0,
      frameMax: 6,
      milisecondAnimation: 2500,
      milisecondTimer: 2500,
      sessionNumber: 22,
    ),
  ];
}
