import '../screens/actionScreen.dart';

class WarmUpNavigator {
  static List<ActionScreen> list = [
    ActionScreen(
      title: 'Butt Bridge',
      number: 10,
      gifDirectory: "assets/gifs/butt-bridge.gif",
      frameMin: 0,
      frameMax: 2,
      milisecondAnimation: 2500,
      milisecondTimer: 2500,
      sessionNumber: 1,
    ),
    ActionScreen(
      title: 'Cross Arm Crunch',
      number: 8,
      gifDirectory: "assets/gifs/cross-arm-crunches.gif",
      frameMin: 0,
      frameMax: 6,
      milisecondAnimation: 2500,
      milisecondTimer: 2500,
      sessionNumber: 2,
    ),
    ActionScreen(
      title: 'Side Crunches',
      number: 10,
      gifDirectory: "assets/gifs/side-crunches.gif",
      frameMin: 0,
      frameMax: 62,
      milisecondAnimation: 2500,
      milisecondTimer: 1250,
      sessionNumber: 3,
    ),
    ActionScreen(
      title: 'Mountain Climber',
      number: 8,
      gifDirectory: "assets/gifs/mountain-climber.gif",
      frameMin: 0,
      frameMax: 4,
      milisecondAnimation: 2500,
      milisecondTimer: 1250,
      sessionNumber: 4,
    ),
    ActionScreen(
      title: 'Leg Raises',
      number: 6,
      gifDirectory: "assets/gifs/legRaises.gif",
      frameMin: 0,
      frameMax: 140,
      milisecondAnimation: 3000,
      milisecondTimer: 3000,
      sessionNumber: 5,
    ),
    ActionScreen(
      title: 'Skipping Without Rope',
      number: 10,
      gifDirectory: "assets/gifs/jump-rope.gif",
      frameMin: 0,
      frameMax: 9,
      milisecondAnimation: 400,
      milisecondTimer: 800,
      sessionNumber: 6,
    ),
    ActionScreen(
      title: 'Warm-up Stretch',
      number: 10,
      gifDirectory: "assets/gifs/runner-warm-up.gif",
      frameMin: 0,
      frameMax: 19,
      milisecondAnimation: 5000,  
      milisecondTimer: 2500,
      sessionNumber: 7,
    ),
    ActionScreen(
      title: 'Cobra Stretch',
      number: 8,
      gifDirectory: "assets/gifs/cobra-stretch.gif",
      frameMin: 0,
      frameMax: 7,
      milisecondAnimation: 3000,
      milisecondTimer: 3000,
      sessionNumber: 8,
    ),
    ActionScreen(
      title: 'Butt Kicks',
      number: 10,
      gifDirectory: "assets/gifs/butt-kicks.gif",
      frameMin: 0,
      frameMax: 44,
      milisecondAnimation: 3200,
      milisecondTimer: 1500,
      sessionNumber: 9,
    ),
    ActionScreen(
      title: 'Jumping Jacks',
      number: 15,
      gifDirectory: "assets/gifs/jumpingJack.gif",
      frameMin: 0,
      frameMax: 40,
      milisecondAnimation: 1500,
      milisecondTimer: 1500,
      sessionNumber: 10,
    ),
    ActionScreen(
      title: 'Forward Bend',
      number: 8,
      gifDirectory: "assets/gifs/stand-and-reach.gif",
      frameMin: 0,
      frameMax: 6,
      milisecondAnimation: 3000,
      milisecondTimer: 3000,
      sessionNumber: 11,
    ),
    ActionScreen(
      title: 'Butterfly Stretch',
      number: 8,
      gifDirectory: "assets/gifs/butterfly-stretch.gif",
      frameMin: 0,
      frameMax: 6,
      milisecondAnimation: 3000,
      milisecondTimer: 3000,
      sessionNumber: 12,
    ),
  ];
}
